export enum ERoutes {
  MAIN = '/',
  UNKNOWN = '*',
  MATCH_MATCH = '/match-match',
  FLAPPY = '/flappy',
  CHESS = '/chess',
  CHESS_OFFLINE = '/chess/offline',
  CHESS_ROOMS = '/chess/rooms',
  CHESS_ROOMS_ID = '/chess/rooms/:id',
  AIM_GAME = '/aim-game',
  NUMBERS = '/2048',
  TIC_TAC = '/tictac',
  SNAKE = '/snake',
  BATTLESHIP = '/battleship',
  BATTLESHIP_ID = '/battleship/:id',
  INVADERS = '/invaders',
  TETRIS = '/tetris',
  REGISTRATION = '/registration',
  LOGIN = '/login',
  SOLITAIRE = '/solitaire'
}
